import { cn } from '@/lib/utils';
import '../styles/globals.css';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import Navbar from '@/components/Navbar';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={cn('antialiased', montserrat.className)}>
      <body className={cn('relative', { 'debug-screens': process.env.NODE_ENV === 'development' })}>
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  );
}
